### ISSUE TITLE
Android kitkat 4.4.4, Blinking Problem

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#8]
I have one user reported this problem.

**Comment by vbresults** [comment]
Fixed in 1.1.31; note that you will have to wait for the app update and then update your app

**Comment by RoldanLT** [comment]
Thanks a lot!

**Comment by RoldanLT** [comment]
This should be open up again, this issue still happening on my user's using Android 4.4.

**Comment by vbresults** [comment]
There may be some misunderstanding here; what do you mean by blinking?

**Comment by RoldanLT** [comment]
The App loads fine for every page, but it keeps the screen blink and blink.
Recent report is here: http://www.phcorner.net/t/phcorner-app.105012/#post-886709
Will try to ask how blinks happen.

**Comment by RoldanLT** [comment]
User said, in every page load, it blinks and it's annoying :(.

**Comment by vbresults** [comment]
Is this only kitkat or every version?  I am trying to reproduce this

**Comment by RoldanLT** [comment]
I only receive report for that Version of Android.

**Comment by vbresults** [comment]
Is this from one person or multiple, if so how many?

**Comment by RoldanLT** [comment]
Only one person report it.

**Comment by vbresults** [comment]
We need a wider set of data, preferably from 3 people, otherwise we don't have enough to work off of.  Closing the ticket for now, if you reply with more input so we can pin down the problem the ticket will be re-opened.
